name: grocery_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  country_code_picker: ^3.2.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/fonts/gilroy/
    - assets/images/grocery_images/
    - assets/images/categories_images/
    - assets/images/beverages_images/
    - assets/icons/account_icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
    # - family: Mulish
    #   fonts:
    #     - asset: assets/fonts/Mulish/Mulish-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Mulish/Mulish-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
    #       weight: 600

  