name: grocery_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  country_code_picker: ^3.2.0
  intl_phone_field: ^3.2.0
  flutter_native_splash: ^2.4.4
  google_sign_in: ^6.3.0
  http: ^1.3.0
  get: ^4.7.2
  flutter_secure_storage: ^9.2.4
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  flutter_polyline_points: ^2.1.0
  location: ^8.0.0
  google_maps_webservice:
    git: https://github.com/danpraise4/google_maps_webservice.git
  iconly: ^1.0.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1


dependency_overrides:
  youtube_explode_dart: 2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.11
  flutter_lints: ^5.0.0
  build_runner: ^2.7.2



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/fonts/gilroy/
    - assets/images/grocery_images/
    - assets/images/categories_images/
    - assets/images/beverages_images/
    - assets/icons/account_icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
    # - family: Mulish
    #   fonts:
    #     - asset: assets/fonts/Mulish/Mulish-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Mulish/Mulish-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
    #       weight: 600

flutter_intl:
  enabled: true
  class_name: AppLocalizations
flutter_native_splash:
  color: "#53B176"
  image: assets/icons/ic_launcher_adaptive_fore.png
  android_12:
    color: "#53B176"
    image: assets/icons/ic_launcher_adaptive_fore.png

  web: false
  